// 构建：src/client.js (ESM) → lib/client.js（DSH 客户端自注册 bundle）
// 契约：window.__ModuleLoader__.load({ id: "<包名>", factory: (require) => module.exports })
// 内核（lib/kernel/）为运行时源码，随包发布，无需构建；此处只做存在性与语法前置校验。
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const src = readFileSync(join(root, 'src', 'client.js'), 'utf8')
  .replace(/^export const /gm, 'const ')
  .replace(/^export function /gm, 'function ')

const out = `/* ${pkg.name} client bundle — generated by scripts/build-client.mjs */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(pkg.name)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${src.replace(/^/gm, '    ')}
    exports.name = name;
    exports.inject = inject;
    exports.apply = apply;
    return module.exports;
  }
});
`
mkdirSync(join(root, 'lib'), { recursive: true })
writeFileSync(join(root, 'lib', 'client.js'), out)
console.log('built lib/client.js (' + out.length + ' bytes) id=' + pkg.name)

for (const f of ['bridge.mjs', 'keeper.mjs', 'second-brain-contract.txt', 'bridge-watchdog.ps1']) {
  const p = join(root, 'lib', 'kernel', f)
  if (!existsSync(p)) throw new Error('kernel artifact missing: ' + p)
  console.log('kernel ok: lib/kernel/' + f + ' (' + readFileSync(p).length + ' bytes)')
}
